const KEY='motoProgressWebV1';
const blank={user:{name:'Umukoresha',phone:'',plate:'',goal:300000,odometer:12000},trips:[],expenses:[],savings:[],goals:[],maintenance:[],reminders:[],debts:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(blank); let page='home';
const rwf=n=>new Intl.NumberFormat('rw-RW',{maximumFractionDigits:0}).format(Math.round(n))+' Frw';
const today=()=>new Date().toISOString().slice(0,10); const daysAgo=n=>{let d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function sum(a,k='amount'){return a.reduce((x,y)=>x+Number(y[k]||0),0)}
function monthTrips(){return db.trips.filter(x=>x.date.startsWith(today().slice(0,7)))}
function monthExp(){return db.expenses.filter(x=>x.date.startsWith(today().slice(0,7)))}
function monthSav(){return db.savings.filter(x=>x.date.startsWith(today().slice(0,7)))}
function profit(){return sum(monthTrips())-sum(monthExp())}
function advice(){const t=monthTrips(),e=monthExp(),p=sum(t),x=sum(e);if(!t.length&&!e.length)return 'Tangira wandika urugendo n’amafaranga wakoresheje kugira ngo nkwereke aho amafaranga yawe ajya.';if(x>p*.35)return 'Amafaranga usohora ari hejuru ugereranyije n’ayo winjiza. Gerageza kureba cyane cyane lisansi n’andi mafaranga yisubiramo.';if(t.length>=2){const avg=p/t.length;return `Umaze gukora ingendo ${t.length} muri uku kwezi, impuzandengo ni ${rwf(avg)} kuri trip. Komeza wandike buri rugendo kugira ngo tumenye iminsi ikwinjiriza cyane.`}return 'Komeza wandike amakuru yawe buri munsi; uko data yiyongera ni ko inama zizaba nziza.'}
function nav(){return `<div class="nav"><div class="navin">${[['home','⌂','Ahabanza'],['trips','↗','Ingendo'],['expenses','↘','Yasohotse'],['savings','◔','Kuzigama'],['moto','⚙','Moto']].map(x=>`<button class="${page==x[0]?'active':''}" onclick="go('${x[0]}')"><span class="ico">${x[1]}</span>${x[2]}</button>`).join('')}</div></div>`}
function header(){return `<header class="top"><div><div class="brand">Moto Progress</div><div class="sub">Gucunga amafaranga no guteza imbere moto</div></div><button class="btn dark" onclick="go('reports')">📊 Raporo</button></header>`}
function card(label,val,cls=''){return `<div class="card"><div class="muted">${label}</div><div class="metric ${cls}">${rwf(val)}</div></div>`}
function home(){const mt=monthTrips(),me=monthExp(),ms=monthSav();const inc=sum(mt),exp=sum(me),sav=sum(ms.filter(x=>x.type==='DEPOSIT'))-sum(ms.filter(x=>x.type==='WITHDRAW'));const goal=db.user.goal||300000;const pct=Math.min(100,Math.max(0,sav/goal*100));return `<div class="content"><div class="welcome"><b>Muraho, ${esc(db.user.name)}! 👋</b><div class="sub" style="color:#182b36;margin-top:5px">Intego y’ukwezi: ${rwf(goal)}</div></div><div class="grid">${card('Winjije uku kwezi',inc,'income')}${card('Wakoresheje uku kwezi',exp,'expense')}${card('Inyungu',inc-exp,'income')}${card('Trips',mt.length)}</div><div class="actions"><button class="btn primary" onclick="modal('trip')">＋ Andika urugendo</button><button class="btn danger" onclick="modal('expense')">− Andika amafaranga</button></div><div class="card section"><b>💡 Inama y’uyu munsi</b><p class="muted">${advice()}</p></div><div class="card section"><div style="display:flex;justify-content:space-between"><b>Kuzigama</b><b>${Math.round(pct)}%</b></div><p class="muted">${rwf(sav)} / ${rwf(goal)}</p><div class="progress"><i style="width:${pct}%"></i></div></div><div class="card section"><b>Imikorere y’iminsi 7 ishize</b><div class="chart">${last7Bars()}</div></div></div>`}
function last7Bars(){let vals=[];for(let i=6;i>=0;i--){let d=daysAgo(i);vals.push({d,v:sum(db.trips.filter(x=>x.date===d))})}let max=Math.max(1,...vals.map(x=>x.v));return vals.map(x=>`<div class="bar" style="height:${Math.max(4,x.v/max*125)}px" title="${rwf(x.v)}"><span>${x.d.slice(5)}</span></div>`).join('')}
function listPage(type){let isT=type==='trips', arr=isT?db.trips:db.expenses;return `<div class="content"><div style="display:flex;justify-content:space-between;align-items:center"><h2>${isT?'Ingendo n’Amafaranga':'Amafaranga Yasohotse'}</h2><button class="btn ${isT?'primary':'danger'}" onclick="modal('${isT?'trip':'expense'}')">＋ Andika</button></div><div class="card">${isT?`Total: <b class="income">${rwf(sum(arr))}</b>`:`Total: <b class="expense">${rwf(sum(arr))}</b>`}</div><div class="list section">${arr.slice().reverse().map((x,i)=>`<div class="row"><div><b>${isT?rwf(x.amount):x.category}</b><div class="muted">${x.date}${isT&&x.pickup?' · '+esc(x.pickup)+' → '+esc(x.dropoff):''}</div></div><div><b class="${isT?'income':'expense'}">${isT?'+':''}${rwf(x.amount)}</b><br><button class="btn dark" style="padding:5px 8px;font-size:11px" onclick="del('${isT?'trip':'expense'}',${db[isT?'trips':'expenses'].indexOf(x)})">Siba</button></div></div>`).join('')||'<div class="empty">Nta makuru arandikwa.</div>'}</div></div>`}
function savings(){let dep=sum(db.savings.filter(x=>x.type==='DEPOSIT')), wit=sum(db.savings.filter(x=>x.type==='WITHDRAW')), bal=dep-wit;return `<div class="content"><div style="display:flex;justify-content:space-between;align-items:center"><h2>Kuzigama</h2><button class="btn primary" onclick="modal('saving')">＋ Kuzigama</button></div>${card('Amafaranga asigaye mu savings',bal,'income')}<div class="section"><button class="btn dark" onclick="modal('goal')">🎯 Shyiraho intego</button></div><div class="list section">${db.goals.map((g,i)=>{let p=Math.min(100,g.current/g.target*100);return `<div class="card"><b>${esc(g.title)}</b><div class="muted">${rwf(g.current)} / ${rwf(g.target)}</div><div class="progress"><i style="width:${p}%"></i></div><div style="margin-top:10px"><button class="btn primary" style="padding:7px" onclick="contribute(${i})">Ongeramo</button> <button class="btn dark" style="padding:7px" onclick="del('goal',${i})">Siba</button></div></div>`}).join('')||'<div class="empty">Nta ntego ufite.</div>'}</div></div>`}
function moto(){return `<div class="content"><h2>Moto yanjye</h2><div class="grid">${card('Kilometero',db.user.odometer)}${card('Service zose',sum(db.maintenance))}</div><div class="actions"><button class="btn primary" onclick="modal('maintenance')">＋ Service</button><button class="btn dark" onclick="modal('reminder')">🔔 Kwibutsa</button></div><div class="card section"><b>Reminders</b><div class="list" style="margin-top:10px">${db.reminders.map((r,i)=>`<div class="row"><div>${esc(r.title)}<div class="muted">${r.date}</div></div><button class="btn dark" onclick="del('reminder',${i})">Siba</button></div>`).join('')||'<div class="empty">Nta byibutsa.</div>'}</div></div><div class="card section"><b>Maintenance</b><div class="list" style="margin-top:10px">${db.maintenance.slice().reverse().map(x=>`<div class="row"><div>${esc(x.type)}<div class="muted">${x.date} · ${x.km} km</div></div><b>${rwf(x.amount)}</b></div>`).join('')||'<div class="empty">Nta service zanditswe.</div>'}</div></div></div>`}
function reports(){const inc=sum(db.trips),exp=sum(db.expenses),sav=sum(db.savings.filter(x=>x.type==='DEPOSIT'))-sum(db.savings.filter(x=>x.type==='WITHDRAW'));return `<div class="content"><h2>Raporo</h2><div class="grid">${card('Amafaranga yose yinjiye',inc,'income')}${card('Amafaranga yose yasohotse',exp,'expense')}${card('Inyungu',inc-exp,'income')}${card('Savings',sav,'income')}</div><div class="card section"><b>Ibiciro by’amafaranga yasohotse</b><div class="list" style="margin-top:10px">${Object.entries(db.expenses.reduce((a,x)=>(a[x.category]=(a[x.category]||0)+x.amount,a),{})).sort((a,b)=>b[1]-a[1]).map(x=>`<div class="row"><span>${esc(x[0])}</span><b>${rwf(x[1])}</b></div>`).join('')||'<div class="empty">Nta expenses.</div>'}</div></div><div class="card section"><b>Umwirondoro</b><p class="muted">${esc(db.user.name)} · ${esc(db.user.phone||'Nta phone')} · Moto ${esc(db.user.plate||'Nta plaque')}</p><button class="btn dark" onclick="modal('profile')">Hindura amakuru</button></div></div>`}
function modal(type){let title='',body='';if(type==='trip'){title='Andika urugendo';body=form([['amount','Amafaranga yishyuwe','number'],['date','Itariki','date'],['pickup','Aho yavuye','text'],['dropoff','Aho yajyaga','text'],['notes','Icyitonderwa','text']],'saveTrip')}else if(type==='expense'){title='Andika amafaranga yasohotse';body=form([['amount','Amafaranga','number'],['date','Itariki','date'],['category','Icyiciro (Lisansi, Repair...)','text'],['notes','Icyitonderwa','text']],'saveExpense')}else if(type==='saving'){title='Kuzigama';body=form([['amount','Amafaranga','number'],['date','Itariki','date'],['type','Ubwoko (DEPOSIT cyangwa WITHDRAW)','text'],['notes','Icyitonderwa','text']],'saveSaving')}else if(type==='goal'){title='Intego yo kuzigama';body=form([['title','Izina ry’intego','text'],['target','Amafaranga ugamije','number'],['current','Ayo watangiranye','number'],['date','Itariki yo kugeraho','date']],'saveGoal')}else if(type==='maintenance'){title='Service ya moto';body=form([['type','Ubwoko bwa service','text'],['amount','Igiciro','number'],['km','Kilometero','number'],['date','Itariki','date']],'saveMaintenance')}else if(type==='reminder'){title='Icyibutsa';body=form([['title','Icyo nkwibutsa','text'],['date','Itariki','date']],'saveReminder')}else {title='Umwirondoro';body=form([['name','Amazina','text'],['phone','Telefone','text'],['plate','Plaque ya moto','text'],['goal','Intego y’ukwezi','number'],['odometer','Kilometero ya moto','number']],'saveProfile')}document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modalbox"><div class="modalhead"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div>${body}</div></div>`)}
function form(fields,fn){return `<form class="form" onsubmit="${fn}(event)">${fields.map(([id,label,type])=>`<label class="muted">${label}<input id="f_${id}" type="${type==='number'?'number':type}" ${id==='date'?'value="'+today()+'"':''} ${type==='number'?'step="1" min="0"':''} required></label>`).join('')}<button class="btn primary" type="submit">Bika</button></form>`}
function val(id){return document.getElementById('f_'+id)?.value||''}function closeModal(){document.getElementById('modal')?.remove()}
function saveTrip(e){e.preventDefault();db.trips.push({amount:+val('amount'),date:val('date'),pickup:val('pickup'),dropoff:val('dropoff'),notes:val('notes')});closeModal();save()}
function saveExpense(e){e.preventDefault();db.expenses.push({amount:+val('amount'),date:val('date'),category:val('category')||'Ibindi',notes:val('notes')});closeModal();save()}
function saveSaving(e){e.preventDefault();db.savings.push({amount:+val('amount'),date:val('date'),type:(val('type')||'DEPOSIT').toUpperCase(),notes:val('notes')});closeModal();save()}
function saveGoal(e){e.preventDefault();db.goals.push({title:val('title'),target:+val('target'),current:+val('current')||0,date:val('date')});closeModal();save()}
function saveMaintenance(e){e.preventDefault();db.maintenance.push({type:val('type'),amount:+val('amount'),km:+val('km'),date:val('date')});db.user.odometer=Math.max(db.user.odometer,+val('km'));closeModal();save()}
function saveReminder(e){e.preventDefault();db.reminders.push({title:val('title'),date:val('date')});closeModal();save()}
function saveProfile(e){e.preventDefault();db.user={...db.user,name:val('name'),phone:val('phone'),plate:val('plate'),goal:+val('goal')||300000,odometer:+val('odometer')||0};closeModal();save()}
function contribute(i){let a=prompt('Andikamo amafaranga uzigamaho:');a=Number(a);if(a>0){db.goals[i].current=Math.min(db.goals[i].target,db.goals[i].current+a);db.savings.push({amount:a,date:today(),type:'DEPOSIT',notes:'Intego: '+db.goals[i].title});save()}}
function del(t,i){if(confirm('Urashaka gusiba?')){let k={trip:'trips',expense:'expenses',goal:'goals',reminder:'reminders'}[t];db[k].splice(i,1);save()}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function go(p){page=p;render()}function render(){let main=page==='home'?home():page==='trips'?listPage('trips'):page==='expenses'?listPage('expenses'):page==='savings'?savings():page==='moto'?moto():reports();document.getElementById('app').innerHTML=header()+main+nav()}
render();
